version: '3.1'

services: 
  web:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    ports:
      - '80:80'
    networks:
      - apinet
  api:
    build:
      context: .
      dockerfile: Dockerfile_flask
    networks:
      - apinet


networks:
  apinet: